#!/usr/bin/ruby

# intro boilerplate
puts <<HEADER
# Unixdaemon Puppet-lint Plugin Repository

This meta-repo exists as a convenient, single location, introduction
to all my `puppet-lint` plugins. Below you'll find a brief introduction
to each plugin and a link to the repo that contains it.

HEADER


# extract and print the intro from each puppet-lint plugin
Dir['puppet-lint*-check'].sort.each do |dir|
  repo_url="https://github.com/deanwilson/#{dir}"
  contents = File.read(File.join(dir, 'README.md'))

  contents.match(/(.+)## Install/m)

  # make the plugin section a level lower and empty line pad it
  intro = "##{$1}\n\n"
  # convert the title in to a link
  intro.sub!(/^## (.*)\n/, "## [\\1](#{repo_url})")

  puts intro
end


# show some other plugin locations
puts <<FOOTER

## Other puppet-lint plugins

You can find information on other useful `puppet-lint` plugins in a few
other locations:

 * [puppet-lint.com/plugins](http://puppet-lint.com/plugins/) Some plugins mentioned on the puppet-lint homepage
 * [Vox Pupuli puppet-lint](https://voxpupuli.org/plugins/#puppet-lint) A collection of code
 donated and maintained by a group of individual puppet users.
 * [GitHub Puppet-lint search](https://github.com/search?utf8=%E2%9C%93&q=puppet-lint+check&type=Repositories&ref=searchresults)

### Author

[Dean Wilson](http://www.unixdaemon.net)

#### Notes

This readme is generated by the hacky `scripts/extract-readme.rb` script in this repo.

FOOTER
